spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:monolith}
spring.datasource.username=${DB_USERNAME:monolith}
spring.datasource.password=${DB_PASSWORD:monolith}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.edu.escuelaing.arep.monolith.config.SecurityConfig=DEBUG
